---
abstract: 'Mojolicious plugin for autoindex function at static resource'
author:
  - 'ChinaXing(陈云星) <chen.yack@gmail.com>'
build_requires:
  Mojolicious::Lite: 0
  Test::Mojo: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-AutoIndex
requires:
  Mojo::Base: 0
  Mojolicious: 4.0
  strict: 0
  warnings: 0
version: 0.0001
